// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NursingHouseService.Models
{
    public partial class checkPatientResult
    {
        public int pId { get; set; }
        public string p姓名 { get; set; }
        public string e員工姓名 { get; set; }
        public string rb床號 { get; set; }
    }
}
