// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NursingHouseService.Models
{
    public partial class TActivityComment
    {
        public int AcId { get; set; }
        public int Ac活動編號 { get; set; }
        public int Ac會員Id { get; set; }
        public double Ac評價 { get; set; }
        public string Ac備註 { get; set; }

        public virtual TMember Ac會員 { get; set; }
        public virtual TActivity Ac活動編號Navigation { get; set; }
    }
}