// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NursingHouseService.Models
{
    public partial class TApplicationForm
    {
        public int AppId { get; set; }
        public int PId { get; set; }
        public int EId { get; set; }
        public int FamId { get; set; }
        public int? OId { get; set; }
        public string App申請人 { get; set; }
        public string App陪同人員 { get; set; }
        public string App聯絡方式 { get; set; }
        public DateTime App申請日期 { get; set; }
        public DateTime? App外出日期 { get; set; }
        public string App事由 { get; set; }
        public string App地點 { get; set; }
        public DateTime? App出發時間 { get; set; }
        public int App預計外出時間 { get; set; }
        public DateTime? App返回時間 { get; set; }
        public string App審核 { get; set; }
        public DateTime? App修改時間 { get; set; }
        public int? App修改人員 { get; set; }
        public int? App現況 { get; set; }
        public string App結案 { get; set; }
        public string App備註 { get; set; }

        public virtual TEmployee EIdNavigation { get; set; }
        public virtual TFamilyMembers Fam { get; set; }
        public virtual TPatientInfo PIdNavigation { get; set; }
    }
}