// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NursingHouseService.Models
{
    public partial class TRoombed
    {
        public TRoombed()
        {
            TBed = new HashSet<TBed>();
        }

        public int RbId { get; set; }
        public string Rb房型 { get; set; }
        public string Rb床號 { get; set; }
        public string Rb空床 { get; set; }
        public DateTime? Rb建立日期 { get; set; }
        public string Rb建立者工號 { get; set; }
        public DateTime? Rb修改日期 { get; set; }
        public string Rb修改者工號 { get; set; }

        public virtual ICollection<TBed> TBed { get; set; }
    }
}