// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace preNursingHouse.Models
{
    public partial class TEmployee
    {
        public TEmployee()
        {
            TActivity = new HashSet<TActivity>();
            TApplicationForm = new HashSet<TApplicationForm>();
            TNursingRecord = new HashSet<TNursingRecord>();
            TOffService = new HashSet<TOffService>();
            TOrder = new HashSet<TOrder>();
            TPatientInfo = new HashSet<TPatientInfo>();
            TShift = new HashSet<TShift>();
            TTake = new HashSet<TTake>();
        }

        public int EId { get; set; }
        public string E員工編號 { get; set; }
        public string E員工姓名 { get; set; }
        public string E電話 { get; set; }
        public string EEmail { get; set; }
        public string E地址 { get; set; }
        public string E密碼 { get; set; }
        public string E性別 { get; set; }
        public string E身分證號 { get; set; }
        public string E職稱 { get; set; }
        public DateTime? E到職日期 { get; set; }
        public DateTime? E離職日期 { get; set; }
        public int? E權限 { get; set; }
        public DateTime? E建立日期 { get; set; }
        public string E建立者工號 { get; set; }
        public DateTime? E修改日期 { get; set; }
        public string E修改者工號 { get; set; }
        public DateTime? E員工生日 { get; set; }
        public string EImagePath { get; set; }

        public virtual ICollection<TActivity> TActivity { get; set; }
        public virtual ICollection<TApplicationForm> TApplicationForm { get; set; }
        public virtual ICollection<TNursingRecord> TNursingRecord { get; set; }
        public virtual ICollection<TOffService> TOffService { get; set; }
        public virtual ICollection<TOrder> TOrder { get; set; }
        public virtual ICollection<TPatientInfo> TPatientInfo { get; set; }
        public virtual ICollection<TShift> TShift { get; set; }
        public virtual ICollection<TTake> TTake { get; set; }
    }
}